### ISSUE TITLE
Add postcss-import and vendor layer

### ISSUE THREAD

**Issue by kmonahan** [forumone/nextjs-project#105]
Add a vendor layer for third-party CSS files, so that components can override them, and add postcss-import to allow for importing of and inlining CSS files from node_modules.

Example use case: adding the base slider styles from SplideJS

**Comment by SirJohn96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NEXTJS-105](https://trello.com/c/07ZMMSNU/836-nextjs-105)
