### ISSUE TITLE
Port modal from Gesso

### ISSUE THREAD

**Issue by coreylafferty** [forumone/nextjs-project#121]
We recently added a modal component to Gesso. This should be ported over to nextjs-project and adjusted as necessary.

Gesso modal PR: https://github.com/forumone/gesso/pull/855

**Comment by SirJohn96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NEXTJS-121](https://trello.com/c/qELZMp7a/842-nextjs-121)
