### ISSUE TITLE
Improvements for headless Drupal set-up projects

### ISSUE THREAD

**Issue by kmonahan** [forumone/nextjs-project#163]
1. Address whatever bug prevents the last three lines in `setup-drupal` from running when script is copied into a Drupal project
2. Fix duplicating of lines in .env.local (if still occurring)
3. Separate hooks into a config.hooks.yaml file to make it easier to move hooks into the root projects .ddev directory
4. Add a docker-compose file to the drupal `starterkits` directory that can be copied into the root directory as part of the setup process
5. Update the default .env.local files and remove any other references to Drupal being located at /drupal

**Comment by carsoncho** [comment]
Re #2. I think this only occurs if you run the `ddev setup-drupal` step multiple times as the code there just copies the contents of https://github.com/forumone/nextjs-project/blob/2.x/starterkits/drupal/.env.drupal and puts it into the `.env.local` whenever it's ran.  I know we ran that at least a couple of times when we were code pairing on this initially. 

I'm not sure there's really a _bug_ there. If we get the steps implemented correctly a user shouldn't have to worry about that occurring.
